### ISSUE TITLE
Cannot access to Teams Meeting

### ISSUE THREAD

**Issue by kidpixo** [USGS-Astrogeology/ISIS_TC#119]
Hi,
I cannot access to the Teams meeting : I'm stuck in the Lobby (this is the second time see #111 ).

Should I get some special invitation to be part of the Telecon?

**Comment by AndrewAnnex** [comment]
I think it doesn't start for another hour (MST vs MDT)

**Comment by kidpixo** [comment]
@AndrewAnnex sorry, I check the MST time in my local time, something is off...
Thanks for the info, I cannot make it at my current local time.
