### ISSUE TITLE
Astro Software Management Plan (ISIS Heavy)

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/ISIS_TC#125]
As discussed at the last TC meeting. I am opening this issue to have a venue for questions regarding the ASC software plan for FY21.

- The FY20 plan has been updated to indicate the work that has been completed: [FY20 Plan](https://github.com/USGS-Astrogeology/softwaremanagement/tree/master/FY20)
- The FY21 plan has been created with the work to be undertaken during the coming fiscal year (Oct 1, 2020 to Sept 30 2021): [FY21 Plan](https://github.com/USGS-Astrogeology/softwaremanagement/tree/master/FY21)
- We continue to use the ISIS SAT report to help drive a large part of our development direction. Not so many updates here because many items are either completed or ongoing. The [README](https://github.com/USGS-Astrogeology/softwaremanagement/tree/master/SpecialActionTeam_Review) has the updates as the SAT report and the ASC response are static documents.
- The [Long Term Plan](https://github.com/USGS-Astrogeology/softwaremanagement/blob/master/LongTermPlanning.md) has been updated to indicate how the work we are doing in FY21 relates to the longer term, five year horizon, planning ASC does.

The ASC team and I are happy to discuss any ISIS related questions that the TC has. If we can get those questions at least a few days before the next meeting (10.13.2020), that would be ideal.

**Comment by rbeyer** [comment]
I see that extracting and modularizing the PVL text parsing/writing functionalities is on the list.  Is the plan to implement a full C++ PVL library (or modify an existing library, like [this one](https://pirlwww.lpl.arizona.edu/software/idaeim/PVL/) )?  Or do you plan to leverage the newly rebuilt Python `pvl` library and embed it somehow (so you don't have to rebuild all the parsing logic)?

**Comment by jessemapel** [comment]
@rbeyer The plan is to get the PVL component of ISIS compiling by itself and using a std::String API. It likely won't be distributed separately, but it's a first step towards having some sort of a core module for ISIS. The hope is that eventually we have a library that contains just the most basic parts of ISIS; Cubes, Cameras, Process objects maybe, etc. Currently, I'm planning on adding a QT interface wrapper to ISIS for compatibility.

I don't think we can use the python PVL library. For the pre-1.0 version we found that it had some speed/memory issue when parsing very large PVL files, such as the kerneldbs used in spiceinit. I haven't re-tested in 1.0, though.

**Comment by rbeyer** [comment]
The 1.0.0 version wasn't particularly tested for speed or extremely large files, so no optimization has been done, however the parsing engine was completely rewritten (that doesn't mean it is faster, only that it is different).  My point is only that PVL text parsing and encoding has a variety of subtleties, and I'm pretty confident that the new Python `pvl` library is handling those subtleties, and if you could benefit from that, that would be good, but I appreciate that you may not be able to.

**Comment by AndrewAnnex** [comment]
"Develop as easy as installtion process as possible to have ASP and ISIS installed in the same conda environment"

besides fixing the typo, I feel like this issue should be rephrased to "updating the conda configuration/updating to newer versions of dependencies provided by the conda-forge channel instead of the usgs-astrogeology channel", which may be the action to take to make the two work together better. From what I have seen on ubuntu I am now able to install asp and isis into the same environment fairly easily as of a few weeks ago, although this may not be true for all platforms.

**Comment by michaelaye** [comment]
who wants to see a thesis abstract as a github issue title? Does the HTML title field even allow that many characters?? :-P

**Comment by jlaura** [comment]
@AndrewAnnex Thanks for spotting the typo.

I feel like we aren't on the same page about the role of the TC. Perhaps I am being overly sensitive reading the comment above! I will preemptively apologize if I am misreading your intent. I do want to make sure that we are on the same page and that is especially challenging given the infrequency of our meetings.

The posted roadmap is not flexible in the sense that, we have identified and funded the tasks that we (ASC) are undertaking. The TC is not a review entity for the project direction. The ISIS project contributors, associated funders, and any review team designated by said funders are able, to varying degrees, to set the tasks and project direction.  I can appreciate that the installation process has gotten easier, but the issue and intent behind my post is not to solicit review from this group [as that is out of scope for what this group agreed its purview was](https://github.com/USGS-Astrogeology/ISIS_TC/blob/master/TC-Charter.md#section-4-responsibilities-of-the-tc). 

The goal of my post is to generally keep this group informed, as a courtesy, of what one set of contributors is doing and answer any questions as they relate to the direction of the project. I believe we all benefit from questions that are raised about the tasks we (ASC) are undertaking. 

Perhaps I am misreading your comment and it is a 'have we considered' question.

**Comment by AndrewAnnex** [comment]
Oh I assumed the issue was posted for as a request for comments. Never mind then

-Andrew Annex

**Comment by jessemapel** [comment]
I'm going to close this issue as there hasn't been new discussion. You can continue to follow our progress on these things at the software management repo.
