### ISSUE TITLE
Astro FY22 Project Planning

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/ISIS_TC#132]
All, 

At ASC we are going project planning for FY22. It is my intention to do most of this work publicly and transparently. To that end, I have created multiple posts on AstroDiscuss to provide insight into what ASC is planning to do next year, provide insight into the process that is being used, and to offer an opportunity for everyone to contribute to the 'what' aspects of our software portfolio.

https://astrodiscuss.usgs.gov/t/fy22-software-project-prioritization/564

I am soliciting comments on our individual project ideas and the overall priority of projects this week (1.25-1.29). 

Many thanks for your participation.

**Comment by jlaura** [comment]
**Bump** - I am going to be locking the FY22 ASC project prioritization threads on AstroDiscuss close of business Friday. Please take some time to check out the posts (linked above) if you are interested in contributing to the *what* aspects of the ASC portfolio.

**Comment by jessemapel** [comment]
@jlaura Would it be reasonable to post this over on the main ISIS repo too?

**Comment by jlaura** [comment]
Sure? This isn't really an issue for the ISIS repository, but the more eyes, the better.

**Comment by jlaura** [comment]
All, I am keeping commenting open until Wednesday 2.3. This is THE opportunity to provide input on the *what* that ASC is planning to undertake next year. Please make sure to comment if you are interested in supporting direction setting for what major development efforts will occur next year. Thanks!

**Comment by jlaura** [comment]
All - just a reminder that today is the last day to comment. Thanks to everyone that has commented already, your feedback is very appreciated.

**Comment by jlaura** [comment]
I am going to close this and will open a new issue once I get the FY22 project synopses posted over on the ASC software management board.
