### ISSUE TITLE
Collecting and Discussing large changes to ISIS

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/ISIS_TC#133]
There has been a lot of discussion in the TC and at Astrogeology Science Center (ASC) about how we publicly propose, discuss, and evaluate large changes to ISIS.

Currently we have several mechanism for this:

* Issues & pull requests
  * This has worked well for small scale changes
  * We have seen both ASC devs and external devs go through this and it has been successful
  * We have had contributors post enhancement requests and even though there is community interest, changes haven't moved past an issue
* Requests for Comment
  * We have had [6 RFCs](https://github.com/USGS-Astrogeology/ISIS3/issues?q=is%3Aissue+label%3ARFC+is%3Aclosed)
  * Most of these have attracted good comments from the community
  * Only ASC devs and projects have gone through this
  * It is unclear what the final product of an RFC is
* Astrodiscuss
  * In preparation for the FY22 portion of the USGS ASC Inter-Agency Agreement with NASA we are developing our proposals publicly on astrodicuss to get community input on priority and deliverables
  * This is very new and it's not clear what the final result will be

I am glad to see experimentation, but I am concerned about the inconsistency and would like easier ways to have a quick-view of what big changes the community would like to see and where they are at in terms of progress. For example, we recently went through brainstorming proposal ideas for the USGS ASC IAA with NASA and having a collection of big changes to reference for ideas would have been very helpful. Similarly, people are seeking funding through other means, such as PDARTs, to contribute to ISIS. Having big changes already posted and discussed would help bolster that effort. Finally, I would love to see ISIS participate in other open source efforts, like Google Summer of Code, that require clearly defined goals.

When working on changes to ISIS I also constantly find myself asking if this needs an RFC. There is a fair amount of ambiguity in the RFC docs we have. Besides what needs and RFC, I've also been wondering what to expect after an RFC is opened or closed.

This is not a problem unique to ISIS, several open source software projects have tackled this issue:

* Python uses [PEPs](https://www.python.org/dev/peps/pep-0001/)
* OpenCV uses [Evolution Proposals](https://github.com/opencv/opencv/wiki/Evolution-Proposals)

So, I have a couple questions that I would like some feedback on:

1. Is this a problem? Am I missing something and this isn't an issue?
2. What are the most important features for a mechanism to track this?
3. Are there other examples out there that we should look at?

**Comment by rbeyer** [comment]
Hmm, I don't know that I have particularly profound ideas about your bigger questions.  There is clearly a need for a mechanism to discuss larger changes before we get down into the weeds of implementation.  As you point out, there are a variety of mechanisms for this out in the wild, we seem to be using this RFC process and Astrodiscuss for it.

Semantically, a "request for comments" is different than a "discussion" and is different than a "proposal."  Logically, you'd probably have a discussion first (Astrodiscuss, maybe via GitHub Issues), then you might write a proposal (something like a PEP or an EP), and then you might have an RFC period on that proposal.  I'm not sure that there's anything particularly broken about our current approach, only that we don't have a clean mechanism for whatever a "proposal" is.  So far all of those things have sourced at ASC, which we've seen move directly to RFC, which is fine.  If an external group or some hybrid group of folk had nucleated enough of a discussion to move on to a proposal, it isn't clear how to do that, but I'm sure we could figure something out that would be reasonable.  Maybe it is worth trying to build that mechanism formally at this time?  Maybe not?

As far as some of your specific questions: "What is the final product of an RFC?"  I think the final product of an RFC is a modified (or unchanged) proposal, which then can be used as a blueprint for implementation to which Issues and PRs can be referenced.  Does someone need to track the implementation plan in such a proposal to ensure that it is completed?  Not sure how to do that.

"What is the final result of the ASC FY22 Astrodiscuss planning?"  This seems obvious to me, so I'm probably missing something.  Seems like the final result is what ASC will propose (or maybe carry out, not sure which side of decision this is on) for the coming FY.  This is really about the activities of a group (ASC) that will be working on an open project.  The fact that ASC shared that plan, and sought input, is a management decision, and the results are ultimately of use to that private group.  I could also post the "Ross Beyer FY22 ISIS development plan" if I wanted input on my ISIS development activities, and I can do what I want with the results.  Whether any of these discussions lead to larger proposals or just Issues or PRs is up to the individuals.

**Comment by jessemapel** [comment]
> "What is the final result of the ASC FY22 Astrodiscuss planning?" This seems obvious to me, so I'm probably missing something. Seems like the final result is what ASC will propose (or maybe carry out, not sure which side of decision this is on) for the coming FY. This is really about the activities of a group (ASC) that will be working on an open project. The fact that ASC shared that plan, and sought input, is a management decision, and the results are ultimately of use to that private group. I could also post the "Ross Beyer FY22 ISIS development plan" if I wanted input on my ISIS development activities, and I can do what I want with the results. Whether any of these discussions lead to larger proposals or just Issues or PRs is up to the individuals.

For this, I am wondering how posting them on astrodiscuss relates to RFCs because the astrodiscuss posts are requests for comments by themselves. Plus, not everything will move forward and those that do will likely be modified. So, will we write an RFC for some of them or just keep the post updated? Is that up the individual leading the project?

**Comment by rbeyer** [comment]
Ah.  Yeah, our terminology is kind of weird, and we have no procedure.

It seems to me that not all work on the ISIS project needs a proposal, only the big stuff.  How do we categorize what is big?  Not sure.  Maybe we need to sharpen that to have reasonable discussions on the topic?

Since we don't have "proposals" I guess the contents offered for RFC are "proposals."  Some of the tasks discussed in the ASC FY22 Plan may not need a "proposal" and can just be worked via Issue/PR.  Some of the tasks may relate to a "proposal" that went through the existing RFC phase, if there needs to be a change to that proposal, then not sure what that mechanism is, but if it is just a task to carry out the work blueprinted in the proposal that went through RFC, then work can just reference that as it creates Issues/PRs.

For "big things" a group of contributors (or a single person) will lead an effort that results in PRs.  Due to the "bigness" a single PR probably isn't going to do it, it may need a feature branch for a while, who knows?  Maybe the effort to address a "big thing" is an application of the "sub-projects" concept defined in our charter.  A group spins up to shepherd the "big thing" (make sure contributors are coordinated, track progress, etc.), and it reports to the ISIS TC.

For "other tasks" that a group of contributors may plan to do that do not relate to a "big thing" then those activities (like some tasks in the ASC FY22 plan) can be carried out with a less formal mechanism, but still openly via Issues/PRs.

**Comment by jessemapel** [comment]
There hasn't been any more discussion in the last month here and there wasn't any more discussion in the TC so I am going to close this and we'll keep moving forward how we have been. We will have a semi-formal RFC process and the normal issue/PR process that developers will decide between as they think is reasonable.
