### ISSUE TITLE
e-calendar for meetings

### ISSUE THREAD

**Issue by AndrewAnnex** [USGS-Astrogeology/ISIS_TC#48]
I rely on electronic calendars to keep track of meetings, could we make a shared calendar so that future meeting issues also require updates to the calendar? There could also be some GitHub integration that would automate this.

**Comment by michaelaye** [comment]
Zoom is able to send invitations, so it could be done via the Zoom linking fro @jlaura

**Comment by jessemapel** [comment]
I personally use google calendar to track all of this stuff. Is there an easy way to integrate that?

**Comment by michaelaye** [comment]
what i'm saying is, if every meeting comes with a calendar appointment attached, we wouldn't need to agree on any calendar system, b/c every participant can do what they need to do with their appointment.

**Comment by victoronline** [comment]
I agree with using some sort of e-calendar for tracking or an agreed upon schedule. As for the calendar attachment, it would work if sent out way in advance. If it's attached the day before, it sort of defeats the purpose.

**Comment by jessemapel** [comment]
If everyone is okay with getting the invitation through the e-mail on their github account, we can use those to send out zoom meeting invites for the next meeting once it's scheduled.

**Comment by jessemapel** [comment]
I've made a google calendar and added the June meeting to it along with a zoom link. I directly shared it, but Michael told me it was blocked for him, can people access it through this link:

https://calendar.google.com/calendar?cid=ZG9pLmdvdl9jb3BraTY2a3Q1dDhpNjZycWJkaGRodm5vY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t

DOI locks certain things down on our usgs.gov google accounts so it could be I need to make this on a private google account.

**Comment by jessemapel** [comment]
It seems the link it's working correctly, I'm going to re-create the calendar on my personal google account and re-share it.

**Comment by jlaura** [comment]
@rbeyer I am inclined to keep this issue here, complete it, update the README on the other repo and then close. No compelling reason to migrate as far as I am concerned.

**Comment by jessemapel** [comment]
See PS TSC
