### ISSUE TITLE
TSC has moved

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/ISIS_TC#53]
The TSC has been moved to https://github.com/PlanetarySoftware/TSC. I would like to remove this repo from the ASC organization and then fork from the PlanetarySoftware organization. Does anyone have concerns with me doing that?

We all need up update our remotes and start working out of the PlanetarySoftware TSC repo.

**Comment by thareUSGS** [comment]
I moved the VICAR/ISIS issue over. If this is something the group doesn't want to tackle it -- that is fine also.

**Comment by jlaura** [comment]
I posted there. We should discuss in the issue. We talked about this for a bit last night, so :+1: for the conversation.

**Comment by jessemapel** [comment]
What happens to links in our meeting notes and such? We'll have to delete this repo and then fork and any issues or PRs referenced will go away.

**Comment by jlaura** [comment]
@jessemapel yes, I believe that links will break. We have just a handful of issues/closed PRs that have links.

**Comment by jessemapel** [comment]
Out of Date
