### ISSUE TITLE
Comments on READ_ME

### ISSUE THREAD

**Issue by rfergason** [USGS-Astrogeology/ISIS_TC#56]
"Candidates for membership tend to be people who have a competency for community management and a high tolerance and patience for process minutiae as the TC delegates most of its responsibilities to other projects and working groups."

I think this text could be deleted and then the remaining line in that paragraph combined with the above paragraph.

**Note - I am able to make these text edits directly to the READ_ME.  I just didn't want to make this change without discussion.

**Comment by rfergason** [comment]
"Current adjacent projects that are within the TC's scope of responsibility include:"

Adjacent projects should be listed, a link to a new page provided, or some indication that there are currently no adjacent projects.

**Comment by jessemapel** [comment]
@rfergason If you want to make changes but you want discussion, you should submit a pull request so that everyone can comment and review on them before they are merged.

**Comment by jessemapel** [comment]
Our next meeting is tomorrow. So, I am going to slot these onto the agenda.

**Comment by jessemapel** [comment]
For the record these changes seem fine to me. I'm not going to add them to tomorrow's agenda because I would like to focus on the charter. If someone else would like to add them to the agenda they can.
