### ISSUE TITLE
Comments on ISIS_TC Charter

### ISSUE THREAD

**Issue by rfergason** [USGS-Astrogeology/ISIS_TC#57]
Section 4: "The meeting shall be directed by the TC Chairperson."

I thought Ross asked whether we would have a Chairperson, and Jesse indicated that this decision was not yet made.  It is up to the TC.  We should then make a decision and ensure that the language in the Charter accurately reflects this decision.

**Comment by rfergason** [comment]
Section 3 vs. Section 5 language:  In Section 5, the bullet "Technical direction." in regards to TC responsibilities is in conflict with the statement in Section 3 "In setting overall technical vision and direction, the ASC Management Team will maintain final judgement on the inclusion of capability within the ISIS Software Package." in regards to ASC Management Team responsibilities.

I would like the Charter to be extremely clear regarding the responsibilities of the ASC management team and the TC, so that there is no confusion or perceived over-stepping of roles as we move forward.  Discussions to ensure that we are all clear and in agreement about these responsibilities would be helpful.

**Comment by rfergason** [comment]
Section 6:  "The development process will establish guidelines for how the developers and community will operate."  I think additional context would clarify this statement (i.e., the developers and community are operating in what venue or tasks?)

Section 6:  "The development process will provide for Projects to follow the lifecycle process..." It may be helpful to explicitly define "the development process" here.

**Comment by jessemapel** [comment]
Our next meeting is tomorrow. So, I am going to slot these onto the agenda.

**Comment by rbeyer** [comment]
We can talk about this in that agenda item tomorrow, but the sentence 

> The ASC Management Team may additionally make amendments to the TC charter at any time, though the ASC Management Team will not interfere with day-to-day discussions, votes or meetings of the TC.

Seems draconian, and seems to go against the grain of the language in the 'Guiding Principales.'  I'd like to chat about this and see if this is some hold-over language from the before-time, or if this is still needed.  I would like to see it dropped.

**Comment by jlaura** [comment]
We should also discuss:

> The ASC Management Team will use the TC as a delegate body for governing technical implementation, individual project scope and direction while they remain within the scope and direction of the policies as described in the TC Policy document and approved by the ASC Management Team.

With a candidate alteration to:

> The ASC Management Team will use the TC as a delegate body for governing technical implementation while they remain within the scope and direction of the policies as described in the TC Policy document and approved by the ASC Management Team.

Also, @rbeyer we should discuss tomorrow. As I read it, the guiding principal is with respect to the TC, not ASC management. I also read the line as saying that ASC management retains ultimate control over the scope of concern that the TC can/should exert responsibility. Good to discuss the scope of responsibilities and roles of how these two groups will interact.

**Comment by jessemapel** [comment]
Discussion of section 3 and relationships between the ASC Management Team and the ISIS TC is in the [November meeting notes](https://github.com/USGS-Astrogeology/ISIS_TC/blob/master/meetings/2019-11-19.md) and in issue #62

**Comment by rbeyer** [comment]
As this got discussed, and further discussion is now in a different Issue, this seems appropriate to close.
