### ISSUE TITLE
TC Charter Comments: Section 1 Guiding Principle

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/ISIS_TC#60]
This issue is for comments and proposed changes to section 1 of the [TC Charter](https://github.com/USGS-Astrogeology/ISIS_TC/blob/master/TC-Charter.md#section-1-guiding-principle).

**Comment by jlaura** [comment]
My take away here is that we have successfully bookend the discussion with pretty solids sections 1 and 9. 🎉

**Comment by rbeyer** [comment]
No significant comments.  Closing.

**Comment by jessemapel** [comment]
If anyone has comments on this section please re-open.
