### ISSUE TITLE
TC Charter Comments: Section 2 Evolution of ISIS Software Project Governance

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/ISIS_TC#61]
This issue is for comments and proposed changes to section 2 of the [TC Charter](https://github.com/USGS-Astrogeology/ISIS_TC/blob/master/TC-Charter.md#section-2-evolution-of-isis-software-project-governance).

**Comment by rbeyer** [comment]
**Regarding Paragraph 1**

I think the opening paragraph here is an echo of a copied document, maybe.  Mostly, there is no 'business' aspect to ISIS.  There are no copyrights, trademarks, or other legal assets that would require a 'business' entity.  Historically, the ASC has exclusively held the 'technical leadership' role, and has contributed nearly 100% of the 'effort' that has developed ISIS.

I think we should re-factor this paragraph to eliminate the 'business leadership' concept, as I don't think it applies.

**Comment by rbeyer** [comment]
**Regarding Paragraph 2**

I think that saying that the ASC can unilaterally meddle with the TC charter at any time is broken, and violates the 'guiding principles' in Section 1.  This is a hill I will die on, meaning that I will vociferously object to keeping it in, barring us from reaching consensus on accepting the Charter and going forward.  If everyone else thinks this language is fine, then I will happily bow out of this process, and wish you all well.

However, such an inherent contradiction in your Charter may make it difficult for it to be accepted by the Planetary Software Organization.

Absolutist statements aside, now that I have your attention, I think there's a simple answer that comes back to this 'theory of control' that we talked about in the telecon, and I suspect this language arose from an earlier realization of this process, which I hope has evolved.  Certainly, if the ASC felt that 'important' aspects of ISIS project management were placed in the TC's Responsibilities (Section 5), then one can imagine that they'd want this unilateral control of the TC.  Instead, I suggest that only those elements that ASC management is willing to 'let go' be placed in Section 5, then this unilateral language can be removed from this section.

**Comment by jessemapel** [comment]
This the tehcnical/business split is an echo of the node.js charter. As @rbeyer stated, ISIS is public domain and thus no one owns it.

The ASC's ability to move unilaterally is the same as everyone else involved in the ISIS TC. As @rbeyer stated, everyone is involved with this voluntarily. I would like to see the ASC management's ability to unilaterally modify the TC charter removed because if that is required, the entire ISIS TC has failed. The only way this whole thing works, is if we all agree that anyone moving unilaterally against the others is a bad idea.

**Comment by rfergason** [comment]
I'm assuming that @rbeyer is referring to the statement "The ASC Management Team may additionally make amendments to the TC charter at any time."  Maybe I'm naive, but I didn't read that statement as ASC management having unilateral control over the TC.  I simply read it as unclear text that should be modified to be consistent with the rest of the document.  For these discussions, it would be helpful if best intentions are first assumed.

**Comment by rfergason** [comment]
Suggested phrasing:
Original: The ASC Management Team may additionally make amendments to the TC charter at any time, though the ASC Management Team will not interfere with day-to-day discussions, votes or meetings of the TC.

Suggested: The ASC Management Team may additionally make amendments to the TC charter at any time, and these changes will be reviewed by the TC per above process. The ASC Management Team will not interfere with day-to-day discussions, votes or meetings of the TC.

**Comment by rfergason** [comment]
I would like to further discuss the statement "the proposed changes being subject to review and approval by the ASC Management Team" as this statement may also be troubling @rbeyer.  I think the intent of this statement is to protect the ASC from the TC making changes to the Charter that ASC management cannot uphold.  If we reach such an impasse, then indeed the ISIS TC and ASC management will have a significant challenge to work through (note I did not call such a disagreement a failure).  I see both sides of this issue and feel there is enough gray in Section 5 that some statement such as this should be discussed.  We need some agreement on how such impasses would be handled, should the arise.

**Comment by jlaura** [comment]
I can appreciate the point of friction here and have enjoyed reading these issues in reverse order. I do not think that ASC management needs to maintain any unilateral control over the TC and second Jesse's comment that things are really broken if we get to that point. 

We have had some conversation across these issues about the fact that the TC can not tell contributors what to do. They can tell contributors how to do it though. I wonder if we can't get something like:

> Most large, complex open source communities have a community of motivated contributors and a set of supporting policies that describe how the community strives to operate, e.g., the technical governance model. ISIS’s technical leadership is the Technical Committee (“TC”). ISIS’s contributor community are all of those participants making substantive contributions to the ISIS project.

> The TC's role is to set policy such as contribution guidelines or release timelines, define and maintain overall project scope, and potentially mediate charged or contentious concerns between contributors. The contributing community takes overall technical ownership of the project and are the 'doers' that get the tangible work done that users depend upon. The contributing community and TC work together to define, maintain and uphold the community norms (contributing community) and then to codify those norms are project policies to ensure shared expectations (TC).

I can see some concern with having the contributors be empowered like this. Aren't the only contributors at ASC? In the short term, many are (but definitely not all!). In the longer term, I sure hope that we can build out a community of contributors that work together on the package so many of us use.
