### ISSUE TITLE
TC Charter Comments: Section 3 ASC Management Team’s Role in Setting the ISIS Software Project’s Strategic Direction

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/ISIS_TC#62]
This issue is for comments and proposed changes to section 3 of the [TC Charter](https://github.com/USGS-Astrogeology/ISIS_TC/blob/master/TC-Charter.md#section-3-asc-management-teams-role-in-setting-the-isis-software-projects-strategic-direction).

**Comment by jessemapel** [comment]
Based on discussion in the November meeting, I think this section needs serious rewrites.

As a start, I think the first paragraph is too prescriptive. I would like to see the TC set its own policy with the ASC Management team signing off on it.

**Comment by rbeyer** [comment]
I agree, but I'd go farther and completely remove all mention of 'ASC Management' from this paragraph (and title).  The Technical Committee should govern itself and set its policies and practices.  ASC Management can then decide if they will direct their employees to act on the policies that the TC sets or not.

**Comment by jlaura** [comment]
I would be happy to remove the ASC management lines from this section and allow the project committers be empowered to make the vast majority of the technical decisions. See my comment on section 4 where I think the TC's role is one of scope setting. The people actually doing the work need to be empowered to make the technical changes that they feel are needed. As a community, those committers do a great job enforcing their own norms, and the TC is really only needed when either (1) polices need support or revamping or (2) disputes arise. With a TC focusing on what the scope is we do not need the same level of technical (implementation) expertise in this group as is valuable in the group doing the work.

**Comment by rbeyer** [comment]
Addressed by #92
