### ISSUE TITLE
TC Charter Comments: Section 4 Establishment of the TC

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/ISIS_TC#63]
This issue is for comments and proposed changes to section 4 of the [TC Charter](https://github.com/USGS-Astrogeology/ISIS_TC/blob/master/TC-Charter.md#section-4-establishment-of-the-tc).

**Comment by rbeyer** [comment]
I'd remove the parenthetical statement which contains 'Google Hangout On Air' as I don't think we need a specific example, and also future-proofs the document a bit.

Language about the 'TC Chairperson' needs to be removed.

The final paragraph of the PSO's template (https://github.com/planetarysoftware/TSC/blob/master/Bootstrap-Policies/Charter.md) talks about how not more than half of the members should be affiliated with the same employer.  That seems like a healthy provision to include.
