### ISSUE TITLE
TC Charter Comments: Section 6 ISIS Software Project Operations

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/ISIS_TC#65]
This issue is for comments and proposed changes to section 6 of the [TC Charter](https://github.com/USGS-Astrogeology/ISIS_TC/blob/master/TC-Charter.md#section-6-isis-software-project-operations).

**Comment by rbeyer** [comment]
As I have mentioned for other sections, I think that reference to 'ASC Management' should be removed from this section.  The TC should set these policies, and then ASC Management can direct their employees to act on them or not.

**Comment by jlaura** [comment]
In the second paragraph I think swapping ASC Management to TC would be a good fix. Then strike the final sentence.
