### ISSUE TITLE
TC Charter Comments: Section 7 Voting

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/ISIS_TC#66]
This issue is for comments and proposed changes to section 7 of the [TC Charter](https://github.com/USGS-Astrogeology/ISIS_TC/blob/master/TC-Charter.md#section-7-voting).

**Comment by rbeyer** [comment]
I suggest we remove the final paragraph which indicates an inappropriate level of control by ASC Management over the TC process, given the guiding principles in Section 1.
