### ISSUE TITLE
TC Charter Comments: Section 8 Project Roles

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/ISIS_TC#67]
This issue is for comments and proposed changes to section 8 of the [TC Charter](https://github.com/USGS-Astrogeology/ISIS_TC/blob/master/TC-Charter.md#section-8-project-roles).

**Comment by rbeyer** [comment]
I'd rewrite the first paragraph as follows:

> The TC shall set the policy for where the official software repository should be maintained.

**Comment by jessemapel** [comment]
I would replace the first sentence of the last paragraph

>Collaborators may opt to elevate significant or controversial modifications, or modifications that have not found consensus to the TC for discussion by assigning the tc-agenda tag to a pull request or issue.

with

>Collaborators may opt to elevate significant or controversial modifications, or modifications that have not found consensus to the TC for discussion by submitting a pull request to the next TC meeting agenda.
