### ISSUE TITLE
Can the TC discuss this?

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/ISIS_TC#71]
Are we ready to have a discussion about this?

https://github.com/USGS-Astrogeology/ISIS3/issues/3566

I think we can, but I'd put it after getting the charter finished.

**Comment by AndrewAnnex** [comment]
I think this would be a great first issue to discuss 👍

**Comment by jessemapel** [comment]
The IPWG at the OSIRIS-REX mission has expressed interest in this. I'm going to add it to the meeting agenda for December.
