### ISSUE TITLE
Using hackmd.io for meeting notes

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/ISIS_TC#77]
Currently we have one person working with a local copy of the meeting notes and taking minutes while screen-sharing.

Looking around, [hackmd.io](hackmd.io) looks like a good way to allow for everyone to view and work on notes during the meeting.

Questions I'd like some input on:
* Does the current process work well enough that we don't need to worry about collaborative notes?
* If we do want collaborative notes, Is there a better tool for this?

**Comment by kidpixo** [comment]
From my experiences, meeting notes are a pain and the person writings miss a lot of the discussion.But it is also good having one person dedicated to this. Not sure which way is better, it depends on the final goal. 
Why not a shared Google drive document? I bet most of us already have Google account(s).

**Comment by jessemapel** [comment]
I personally like google docs, but here at the USGS we just lost our google accounts and got switched over to Microsoft Office 365, so google drive is less than ideal.

**Comment by kidpixo** [comment]
> I personally like google docs, but here at the USGS we just lost our google accounts and got switched over to Microsoft Office 365, so google drive is less than ideal.

I didn't know that, I assume in USA the use of Google was widespread...

**Comment by jessemapel** [comment]
> I didn't know that, I assume in USA the use of Google was widespread...

It is fairly wide-spread, but the government contracts it out, so there's regular re-competes and Office 365 won out this year.

**Comment by michaelaye** [comment]
And now, a webapp with the name HACKMD.io is a much more secure and accepted way to operate.. ;). Just teasing, I would be fine with any of the shared markdown services.

**Comment by scsides** [comment]
Google docs may still be a good way to go. USGS people will need to use personal accounts on virtually all services anyway. Access to o365 is spotty at best for most people.

As far as notes go, I've seen good notes taken when one person is responsible for the bulk, but one or two others are adding, and correcting as the meeting moves on.

**Comment by jessemapel** [comment]
Link to a google doc for today's meeting notes:

https://docs.google.com/document/d/1HtLXaVfVRtV9I6KQd0ZOrGHwbP5N9mrWHeoHwRx42ww/edit?usp=sharing

**Comment by jessemapel** [comment]
I enjoyed using google docs for this last meeting. I did not enjoy distributing the edit link and I did a really bad job of taking notes.

So, is there a better way to distribute a google doc edit link? Also I would like to either have someone else lead the next meeting or someone else take notes at the next meeting.
